name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Only run release job on tags
  release:
    types: [created]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  release:
    needs: build
    # Only run release job on tags
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Extract project name
      run: echo "PROJECT_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

    - name: Build release - Linux amd64
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -o $PROJECT_NAME-linux-amd64 ./...

    - name: Build release - Linux arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -o $PROJECT_NAME-linux-arm64 ./...

    - name: Build release - macOS arm64
      env:
        GOOS: darwin
        GOARCH: arm64
      run: go build -o $PROJECT_NAME-darwin-arm64 ./...

    - name: Upload linux amd64 binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }}-linux-amd64
        path: ${{ env.PROJECT_NAME }}-linux-amd64

    - name: Upload Linux arm64 binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }}-linux-arm64
        path: ${{ env.PROJECT_NAME }}-linux-arm64

    - name: Upload macOS arm64 binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }}-darwin-arm64
        path: ${{ env.PROJECT_NAME }}-darwin-arm64
